# Generated by Django 4.1.5 on 2023-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_city_description_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
