# Generated by Django 4.1.5 on 2023-02-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
